# Node.js with React
# Build a Node.js project that uses React.

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Fix: Erst alle Dependencies installieren (mit --legacy-peer-deps, um Konflikte zu vermeiden)
#- script: npm install --legacy-peer-deps
#  displayName: 'Install dependencies with legacy-peer-deps'

# Fix: `env-cmd` erst nach erfolgreicher Installation der Dependencies installieren
#- script: npm install env-cmd --save-dev --legacy-peer-deps
#  displayName: 'Install env-cmd'

# Jetzt erst das Build starten
- script:
    npm install
    npm run build
  displayName: 'npm install and build project'
