trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Caching für node_modules (Performance-Boost)
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    path: '$(npm_config_cache)'
  displayName: 'Cache npm dependencies'

# Install dependencies mit --legacy-peer-deps, falls nötig
- script: |
    npm install --legacy-peer-deps
  displayName: 'Install dependencies'

# Build ausführen (ggf. mit CI=false, falls react-scripts genutzt wird)
- script: |
    npm run build
  displayName: 'Build project'

# Optional: Artefakte veröffentlichen (z.B. für ein Deployment)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'build'
    artifactName: 'drop'
  displayName: 'Publish Build Artifacts'
