# Node.js with React
# Build a Node.js project that uses React.

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Fix: Verwende gleich `--legacy-peer-deps` beim Installieren der Dependencies
- script: npm install --legacy-peer-deps
  displayName: 'Install dependencies with legacy-peer-deps'

# Fix: Installiere `env-cmd` VOR dem Build, damit `npm run build` nicht fehlschlägt
- script: npm install env-cmd --save-dev
  displayName: 'Install env-cmd'

# Jetzt erst das Build starten
- script: npm run build
  displayName: 'Build project'
